apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: jenkins-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "jenkins.bootifulmicropizza.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https-443
      protocol: HTTP
    hosts:
    - "jenkins.bootifulmicropizza.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jenkins
spec:
  hosts:
  - "jenkins.bootifulmicropizza.com"
  gateways:
  - jenkins-gateway
  http:
  - route:
    - destination:
        host: bootifulmicropizza-jenkins.devops.svc.cluster.local
